# Generated by Django 2.2.6 on 2021-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211104_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False, verbose_name='Список покупок'),
        ),
    ]
