# Generated by Django 2.2.6 on 2021-11-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
